from enum import Enum


class Intent(str, Enum):
    CREATE_PLAN = "CREATE_PLAN"
    MODIFY_PLAN = "MODIFY_PLAN"
    CANCEL_PLAN = "CANCEL_PLAN"
    EXPORT_PLAN = "EXPORT_PLAN"
    CALCULATE_COST = "CALCULATE_COST"
    OPTIMIZE_ROUTE = "OPTIMIZE_ROUTE"
    RECOMMEND_PLACE = "RECOMMEND_PLACE"
    SUMMARY = "SUMMARY"
